name: Conditional Workflow

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hola
        run: echo "Hola"
        id: hola-step
      - name: Check Hola Step
        run: |
          if [ "${{ steps.hola-step.outcome }}" != "success" ]; then
            echo "fail"
          else
            echo "success"
          
        id: check-hola
        continue-on-error: true

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs['check-hola'] == 'fail'
    steps:
      - name: Say Adios
        run: echo "Adios"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs['check-hola'] == 'success'
    steps:
      - name: Say Hola Hola
        run: echo "Hola Hola"
